### ISSUE TITLE
Eliminate "com.maulingmonkey.jerk_test.jni_symbols_source" workaround

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/jerk#14]
Invoking `java.lang.System.load("C:/absolute/path/to/the/test.exe")` fails when directly invoked from JNI.  [StackOverflow explains possibly why](https://stackoverflow.com/a/28704831).  As a workaround, I currently load the executable from test-specific Java code - see all references to `com.maulingmonkey.jerk_test.jni_symbols_source`.

**Comment by MaulingMonkey** [comment]
Turns out this hack isn't even fully sufficient on linux.  Specifically, `System.load("...")`ing the executable causes yet another dupe of all symbols.  Lame!

### .cargo/config

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]
```
